/** Central agent-loop tunables — single place to adjust runtime behavior. */
const Tunables = {
  MAX_AGENT_ROUNDS: 10,
  MAX_EDIT_RETRIES_WITHOUT_TOOLS: 1,
  MAX_PLAN_RETRIES_WITHOUT_FILE: 3,
  MAX_VERIFICATION_REMINDERS: 1,
  MAX_FAILED_VERIFICATION_REMINDERS: 1,
  REPEAT_CLASS_LIMIT: 2,
  COMMAND_RESPONSE_BUFFER_CHARS: 220,
  HISTORY_BUDGET_RATIO: 0.75,
  TURN_PROMPT_TOKEN_BUDGET_RATIO: 0.85,
  TURN_WALL_CLOCK_MS: 600_000,
  FAILURE_MEMORY_TTL_MS: 24 * 60 * 60 * 1000,
  APPROVAL_TIMEOUT_MS: 60_000,
  OPERATOR_QUESTIONS_TIMEOUT_MS: 300_000,
  TEMPERATURE_AGENT: 0.1,
  TEMPERATURE_READ_ONLY: 0.2,
  TEMPERATURE_SUMMARY: 0,
  ROUNDS_LEFT_WARNING_THRESHOLD: 3,
  TASK_BRIEF_UPDATE_AFTER_ROUND: 1,
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = Tunables;
}

if (typeof globalThis !== "undefined") {
  globalThis.AgentTunables = Tunables;
}
